### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [xu-minghao317/amazon-historical-prices#2]
Added v1.0.1 to Firefox 115.18.0esr and the price chart doesn't appear on Amazon item pages. The Camel one does.

**Comment by ming-hao-xu** [comment]
Thanks for reporting this issue!
The fix has been shipped in v1.1.0. Please update and check if the chart appears now.

**Comment by GitTheHellOutaHere** [comment]
I can confirm that it is now working. However, the graph is clunky and shows less useful data than the Camel script.

![Keepa script](https://github.com/user-attachments/assets/04681748-b600-4aab-b7d2-7b7df561911d)
https://www.amazon.com/dp/B003SSP2V8?th=1

**Comment by ming-hao-xu** [comment]
Thank you for confirming! The graph relies on Keepa’s rendering, so I can’t control its appearance. However, you can adjust settings like `chartRange` to 365 for a longer range, and clicking the graph provides more details. We use Keepa because it covers more regions globally. Apologies for any inconvenience.

**Comment by GitTheHellOutaHere** [comment]
I don't see that it offers any advantage to CamelCamel, so I will uninstall your script. But now I have serious doubts about how accurate their results truly are.

How is anyone to know that clicking the graph will take you to the Keepa website where you can change the settings? I didn't. Clicking the Camel graph only zooms/unzooms it.

**Comment by ming-hao-xu** [comment]
> I don't see that it offers any advantage to CamelCamel, so I will uninstall your script. But now I have serious doubts about how accurate their results truly are.

Again, this script is aimed at users from different regions, where Keepa is more reliable than CamelCamel. If you’re in the US, CamelCamel might work better for you.

> How is anyone to know that clicking the graph will take you to the Keepa website where you can change the settings? I didn't. Clicking the Camel graph only zooms/unzooms it.

Please refer to the README and the GreasyFork page for details. To adjust settings, you’ll need to modify the code at the top.
